name: Create and Publish chart

on:
  push:
    branches:
      - jae/chartgen

defaults:
  run:
    working-directory: chart-generate

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v4
          with:
            python-version: "3.12"
  
        - name: Install Poetry
          uses: snok/install-poetry@v1
          with:
            virtualenvs-create: true
            virtualenvs-in-project: true
            virtualenvs-path: ./.venv
  
        - name: Install Python dependencies
          run: poetry install --no-root
  
        - name: run script
          run: |
            pwd
            poetry run ./chartgen.py
  
        - name: Deploy ðŸš€
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: ./chart-generate/out